import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbars from "./components/navbars";
import { Providers } from "./provider";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Business School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbars />
        <Providers>
          <div className=" w-full min-h-screen">{children}</div>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
